### ISSUE TITLE
[Feature Request] Use a remote server (OpenAI-compatible API)

### ISSUE THREAD

**Issue by InconsolableCellist** [felixrieseberg/clippy#9]
I have an OpenAI-compatible server that can run a model much larger than what my laptop can run, and thus I'd like to direct Clippy to it rather than running locally. It'd nice if you can point Clippy to an API such as OpenAI or any of the other compatible ones, like llama.cpp, exllama/tabbyAPI, OpenRouter, etc.

**Comment by OlliWare** [comment]
Just chiming in to +1 this, remote OpenAI support would be super helpful.

I’m running Ollama through the OpenAI API on a separate powerful machine and would love for Clippy to be able to connect over the network. It’d make it easier to offload compute, share a central model instance across devices, or work from a lighter laptop setup.

**Comment by thfrei** [comment]
Or LiteLLM as a proxy for example! I think 4 parameters per model should suffice?

- API_BASE_URL
- API_KEY
- MODEL_NAME
- PROVIDER: openai (in the future maybe anthropic / google, as they have slightly different api syntax, I think)

Think like continue setup https://docs.continue.dev/customize/model-providers/openai

```
models: 
  - name: Claude 3.7 Sonnet
    provider: anthropic
    model: claude-3-7-sonnet
    apiBase: https://url...
    apiKey: your-api-key
    roles:
      - chat
      - edit
```
